name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag parttimelegend-bitcoind:$(date +%s)
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      if: steps.extract_branch.outputs.branch == 'master'
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      if: steps.extract_branch.outputs.branch == 'master'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      if: steps.extract_branch.outputs.branch == 'master'
      with:
       context: .
       file: ./Dockerfile
       platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
       push: true
       tags:
         user/app:latest
         user/app:1.0.$GITHUB_RUN_ID
